import { z } from "zod";

/* ================================
   BASE FIELDS
================================ */

const email = z
  .string()
  .email("Invalid email address")
  .toLowerCase()
  .trim();

/*
 * Password max is 72 to match bcrypt's actual input limit.
 * bcrypt silently truncates at 72 bytes — passwords longer
 * than 72 that share the same first 72 chars would collide.
 */
const password = z
  .string()
  .min(8, "Password must be at least 8 characters")
  .max(72, "Password must be at most 72 characters")
  .superRefine((val, ctx) => {
    let score = 0;
    if (/[A-Z]/.test(val)) score++;
    if (/[a-z]/.test(val)) score++;
    if (/[0-9]/.test(val)) score++;
    if (/[^A-Za-z0-9]/.test(val)) score++;

    if (score < 3) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "Password must contain at least 3 of: uppercase, lowercase, digit, special character",
      });
    }
  });

/*
 * Name — Unicode letters, spaces, hyphens, apostrophes, dots.
 * Supports international names including accented characters,
 * suffixes (Jr., III), and compound names.
 */
const name = z
  .string()
  .min(2, "Name must be at least 2 characters")
  .max(60, "Name must be at most 60 characters")
  .regex(
    /^[\p{L}\s'\-\.]+$/u,
    "Name can only contain letters, spaces, hyphens, apostrophes, and dots"
  );

/*
 * OTP — exactly 6 digits.
 */
const otp = z
  .string()
  .length(6, "OTP must be 6 digits")
  .regex(/^\d{6}$/, "OTP must contain only digits");

/*
 * RequestId — 24-character lowercase hex string.
 * Generated by the server via crypto.randomBytes(12).toString("hex").
 * Client must pass back exactly what the server issued.
 */
const requestId = z
  .string()
  .length(24, "Invalid request ID")
  .regex(/^[0-9a-f]{24}$/, "Invalid request ID format");

/* ================================
   SCHEMAS
================================ */

export const signupSchema = z.object({
  name,
  email,
  password,
});

/*
 * Login does not enforce password strength — the DB check
 * will reject wrong passwords regardless. Enforcing strength
 * here would block existing users whose passwords predate
 * the strength rules.
 */
export const loginSchema = z.object({
  email,
  password: z.string().min(1, "Password is required"),
});

/*
 * sendOTP is used for password reset OTP resend only.
 * requestId must be a valid server-issued ID from a previous
 * login or password reset initiation — not client-generated.
 */
export const sendOTPSchema = z.object({
  email,
  requestId,
});

export const verifyOTPSchema = z.object({
  email,
  requestId,
  otp,
});

export const completeOTPLoginSchema = z.object({
  email,
  requestId,
  otp,
});

export const resetPasswordSchema = z.object({
  email,
  requestId,
  otp,
  newPassword: password,
});